# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

# Mod properties
mod.version=1.3.0-alpha.0
mod.group=fr.galsaxx
mod.id=personnalworld
mod.name=PersonnalWorld

# Shared dependencies
deps.fabric_loader=0.18.4
deps.architectury=13.0.8
deps.mixin_extras=0.4.1
