# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

# Mod properties
mod.version=1.2.2
mod.group=fr.galsaxx
mod.id=personnalworld
mod.name=PersonnalWorld

# Shared loader dependency (version-agnostic where possible)
deps.fabric_loader=0.16.14
